server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
app:
  eureka:
    server: discovery-server

spring:
  application:
    name: notification-service

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411